# Pipeline para Evalucion Curso DevOps
# Oscar Frias
# Enero 2023

trigger:
- feature-ms-oscarfrias-mensaje

pool: 'Default'

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Build de Proyecto MS

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'TokenSonarCloud'
    organization: 'devops-oafn'
    projectKey: 'Devops-OAFN_microservicio-spring'
    projectName: 'microservicio-spring'
  displayName: Preparar analisis SonarCloud

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: Realizar analisis con SonarCloud

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'Build Plugin'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    command: 'login'
  displayName: Conexion a Docker

- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'oscarfriasnunez/DevOps-OAFN'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  displayName: Docker File

- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'oscarfriasnunez/DevOps-OAFN'
    command: 'push'
    tags: 'latest'
  displayName: Docker Push  

- task: Kubernetes@1
  inputs:
    connectionType: 'None'
    namespace: 'default'
    command: 'apply'
    arguments: '-f deployment-app.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
  displayName: Desploy de Kubernetes

- task: Kubernetes@1
  inputs:
    connectionType: 'None'
    command: 'expose'
    arguments: 'deployment ms-web-deployment --type=NodePort --name=ms-web-expose'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
  displayName: Exponer Kubernetes


